#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/aston

PRODUCT_COPY_FILES += \
    vendor/oneplus/aston/proprietary/odm/etc/aac_richtap.config:$(TARGET_COPY_OUT_ODM)/etc/aac_richtap.config \
    vendor/oneplus/aston/proprietary/odm/etc/acdbdata/Audio_Parameter_Version.txt:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Audio_Parameter_Version.txt \
    vendor/oneplus/aston/proprietary/odm/etc/acdbdata/FTM/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/acdb_cal.acdb \
    vendor/oneplus/aston/proprietary/odm/etc/acdbdata/FTM/workspaceFileXml.qwsp:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/workspaceFileXml.qwsp \
    vendor/oneplus/aston/proprietary/odm/etc/acdbdata/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/acdb_cal.acdb \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Calibration360_2mic.dat:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Calibration360_2mic.dat \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Configuration.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Configuration.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID10_MIC_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID10_MIC_VR.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID11_HE.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID11_HE.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID12_HE_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID12_HE_APP1.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID13_HE_APP2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID13_HE_APP2.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID14_HE_Cam.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID14_HE_Cam.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID15_HE_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID15_HE_Conference.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID16_HE_Fast.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID16_HE_Fast.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID17_HE_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID17_HE_Interview.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID18_HE_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID18_HE_Unprocess.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID19_HE_Voice.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID19_HE_Voice.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID1_MIC_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID1_MIC_Normal.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID20_HE_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID20_HE_VR.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID21_USB_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID21_USB_Normal.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID22_USB_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID22_USB_APP1.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID23_BT_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID23_BT_Normal.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID24_BT_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID24_BT_APP1.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID25_2mic_zoom.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID25_2mic_zoom.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID2_MIC_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID2_MIC_APP1.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID3_MIC_APP2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID3_MIC_APP2.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID4_MIC_Cam.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID4_MIC_Cam.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID5_MIC_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID5_MIC_Conference.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID6_MIC_Fast.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID6_MIC_Fast.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID7_MIC_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID7_MIC_Interview.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID8_MIC_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID8_MIC_Unprocess.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID9_MIC_Voice.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID9_MIC_Voice.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_1.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_10.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_10.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_11.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_11.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_12.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_12.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_13.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_13.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_14.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_14.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_15.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_15.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_16.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_16.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_17.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_17.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_18.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_18.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_19.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_19.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_2.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_20.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_20.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_21.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_21.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_22.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_22.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_23.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_23.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_24.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_24.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_25.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_25.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_3.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_3.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_4.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_4.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_5.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_5.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_6.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_6.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_7.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_7.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_8.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_8.txt \
    vendor/oneplus/aston/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_9.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_9.txt \
    vendor/oneplus/aston/proprietary/odm/etc/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/mixer_paths.xml \
    vendor/oneplus/aston/proprietary/odm/etc/resourcemanager.xml:$(TARGET_COPY_OUT_ODM)/etc/resourcemanager.xml \
    vendor/oneplus/aston/proprietary/odm/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_ODM)/etc/usecaseKvManager.xml \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/bdwlan.elf \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/bdwlang.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/bdwlang.elf \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/bin_version:$(TARGET_COPY_OUT_ODM)/etc/wifi/bin_version \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/cnss_diag.conf:$(TARGET_COPY_OUT_ODM)/etc/wifi/cnss_diag.conf \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/cnss_diag_always_on.conf:$(TARGET_COPY_OUT_ODM)/etc/wifi/cnss_diag_always_on.conf \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/kiwi/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.elf \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/kiwi/regdb.bin:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/regdb.bin \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/kiwi/regdb_version:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/regdb_version \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/regdb.bin:$(TARGET_COPY_OUT_ODM)/etc/wifi/regdb.bin \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/regdb_version:$(TARGET_COPY_OUT_ODM)/etc/wifi/regdb_version \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/sar-vendor-cmd.xml:$(TARGET_COPY_OUT_ODM)/etc/wifi/sar-vendor-cmd.xml \
    vendor/oneplus/aston/proprietary/odm/etc/wifi/wifisar.cfg:$(TARGET_COPY_OUT_ODM)/etc/wifi/wifisar.cfg \
    vendor/oneplus/aston/proprietary/odm/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_ODM)/firmware/tfa98xx.cnt \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/FW_S3910_BOE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/FW_S3910_BOE.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/FW_S3910_BOE_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/FW_S3910_BOE_FAE.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/FW_S3910_BOE_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/FW_S3910_BOE_HBP.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/FW_S3910_BOE_HBP_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/FW_S3910_BOE_HBP_FAE.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/FW_S3910_TIANMA.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/FW_S3910_TIANMA.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/FW_S3910_TIANMA_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/FW_S3910_TIANMA_FAE.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/FW_S3910_TIANMA_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/FW_S3910_TIANMA_HBP.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/FW_S3910_TIANMA_HBP_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/FW_S3910_TIANMA_HBP_FAE.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/LIB_S3910_BOE_HBP_TS_ALGO.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/LIB_S3910_BOE_HBP_TS_ALGO.so \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/LIB_S3910_BOE_HBP_TS_HAL.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/LIB_S3910_BOE_HBP_TS_HAL.so \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/LIB_S3910_TIANMA_HBP_TS_ALGO.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/LIB_S3910_TIANMA_HBP_TS_ALGO.so \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/LIB_S3910_TIANMA_HBP_TS_HAL.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/LIB_S3910_TIANMA_HBP_TS_HAL.so \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/LIMIT_S3910_BOE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/LIMIT_S3910_BOE.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/LIMIT_S3910_BOE_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/LIMIT_S3910_BOE_HBP.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/LIMIT_S3910_BOE_HBP_AGING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/LIMIT_S3910_BOE_HBP_AGING.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/LIMIT_S3910_TIANMA.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/LIMIT_S3910_TIANMA.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/LIMIT_S3910_TIANMA_HBP.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/LIMIT_S3910_TIANMA_HBP.img \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/libIfp.so:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/libIfp.so \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/sys_edge_touch_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/sys_edge_touch_config.xml \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/sys_touch_algo_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/sys_touch_algo_feature_config.xml \
    vendor/oneplus/aston/proprietary/odm/firmware/tp/23801/sys_touch_function_feature_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/tp/23801/sys_touch_function_feature_config.xml
